---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - common
    - { role: web, when: "ansible_os_family != 'RedHat'" }
