---

  vars:
      ec2_key_name: ansible-tower
      ec2_region: eu-west-1
      ec2_zone: eu-west-1c
      ec2_ami: ami-f8cc838b
      ec2_count: 1
      ec2_public_ip: yes
      ec2_monitor: no
      ec2_group: bpm-ansible-demo
      ec2_subnet: subnet-bc69e8e4
      ec2_wait: yes
      ec2_state: present
      # we use this AWS tag to identify newly provisioned instances
      ec2_instance_tags: '{"type":"freshman"}'

  tasks:

    - name: 'Create Amazon VM Instance(s)'
      ec2:
        # set in vars: above just for convenience
        key_name: "{{ ec2_key_name }}"
        region: "{{ ec2_region }}"
        zone: "{{ ec2_zone }}"
        image: "{{ ec2_ami }}"
        count: "{{ ec2_count }}"
        instance_tags: "{{ ec2_instance_tags }}"
        assign_public_ip: "{{ ec2_public_ip }}"
        monitoring: "{{ ec2_monitor }}"
        group: "{{ ec2_group }}"
        vpc_subnet_id: "{{ ec2_subnet }}"
        wait: "{{ ec2_wait }}"
        state: "{{ ec2_state }}"
        # passed as 'extra_vars' from BPM form input
        instance_type: "{{ ec2_instance_type }}"
      register: newmachines

    - name: Wait for SSH to start
      wait_for:
        host: "{{ newmachines.instances[0].public_ip }}"
        port: 22
        timeout: 300
      delegate_to: localhost

    - name: Add the machine to in memory inventory
      add_host:
        hostname: "{{ newmachines.instances[0].public_ip }}"
        groups: amazon
