---
- name: Disable Users AD Account and SSO
  hosts: all
  gather_facts: false
  ignore_errors: true

  vars:
    # helps define how we'll connect to our Windows host
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:

  - name: Disable Users AD Account
    # until V2.2 we'll need to use script, 2.2 has win_command!
    script: scripts/disable_ad_account.ps1
    register: ad_result
  - debug: var=ad_result

  - name: Disable Octa SSO
    # use win_uri to call a pretend octa SSO API
    win_uri:
      url: https://jsonplaceholder.typicode.com
      method: POST
      body: "{ 'user': 'disable' }"
