---
- name: Steps To Disable Users AD Account
  # we run this on the AD server to save messing with permissions
  #hosts: tag_Name_active_directory_server
  hosts: 52.210.94.75
  # we don't need any host facts so disable to make run faster
  gather_facts: false

  vars:
    # helps define how we'll connect to our Windows host
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    # where we'll put the disablement script
    tmp_dir: 'C:\Temp'
    script: 'disable_ad_account'

  tasks:

  - name: Create {{ tmp_dir }} on server if required
    win_file: path='{{ tmp_dir }}' state=directory

  - name: Create powershell disablement script
    win_template:
      src: 'templates/{{script}}.j2'
      dest: '{{tmp_dir}}/{{script}}.ps1'

  - name: Disable Users AD Account
    # until V2.2 we'll need to use the raw module, 2.2 has win_command!
    raw: '{{tmp_dir}}/{{script}}.ps1'
