---

# This playbook will disable an AD account

- name: Disable users AD account
# Run powershell command to disable AD account
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: run whoami
    win_command: whoami
    register: whoami_out
  - debug: var=whoami_out

- name: Disable users SSO account
# Run Octa SAML 2.0 API call would go here...
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  ignore_errors: true

  tasks:
  - name: test stat module on file
    win_uri:
      url: http://somethinghere.com/api
      method: GET
    register: api_callout
