---
# This playbook provides VM orchestration on Amazon EC2

- name: VM Orchestration
  hosts: all
  connection: local
  gather_facts: no

  pre_tasks:
    - name: Log what we are doing
      shell: /bin/logger 'Going to {{ vm_env_action }} {{vm_env_instances}} VM(s) for provider {{ vm_env_provider }}'

  roles:
    - common
    - { role: offprem, when: vm_env == 'OffPrem' }

  post_tasks:
    - name: Log what we have done
      shell: /bin/logger '{{ vm_env_action }} VM(s) for provider {{ vm_env_provider }} complete'
      
