---
# This playbook provides VM orchestration across on premise and cloud envs

- name: VM Orchestration
  hosts: all
  connection: local
  gather_facts: no

  pre_tasks:
    - name: Log what we are doing
      shell: /bin/logger 'Going to {{ vm_env_action }} VM {{ vm_hostname }} for provider(s) {{ vm_env_provider }}'

  roles:
    - common
    - { role: offprem, when: vm_env == 'OffPrem' }

  post_tasks:
    - name: Log what we have done
      shell: /bin/logger '{{ vm_env_action }} VM {{ vm_hostname }} for provider(s) {{ vm_env_provider }} complete'
