---
- hosts: beckton
  remote_user: vagrant
  gather_facts: false

  tasks:
    - name: Check if user exists
      action: chkuser username=foobar
      register: user

    - debug: msg="{{ user.msg }}"
