---
- name: Setup an EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Basic AMI Creation
      ec2_ami:
        region: eu-west-1
        instance_id: "{{ ec2_instance_id }}"
        wait: yes
        name: "{{ ec2_ami_name }}"
        tags:
          Name: amibuilder
          Service: Build
      register: newmachines
