---
- name: Setup an vsphere ESXI VM
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "username"
      prompt: "Enter vcenter username: "
      private: yes
    - name: "password"
      prompt: "Enter vcenter password: "
      private: yes

  tasks:
    - name: Create an ESXi VM Guest
      vsphere_guest:
        vcenter_hostname: vcenter.gps.hst.ams2.redhat.com
        # version 2.1 only -> validate_certs: no
        username: '{{ username }}'
        password: '{{ password }}'
        guest: mynewvm01
        state: powered_on
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test VM spun up using an Ansible playbook
          #folder: MyFolder
        vm_disk:
          disk1:
            size_gb: 10
            type: thin
            datastore: ds-cloud12-localdisk
            #folder: EMEA CloudLab/Individuals/pgriffit
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
          nic2:
            type: vmxnet3
            network: DPortGroup-Public
            network_type: dvs
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
            #vm_cdrom:
            #  type: "iso"
            #  iso_path: "DatastoreName/cd-image.iso"
            #vm_floppy:
            #  type: "image"
            #  image_path: "DatastoreName/floppy-image.flp"
        esxi:
          datacenter: EMEA CloudLab
          hostname: cloud12-acc.gps.hst.ams2.redhat.com
