---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: update packages
      ignore_errors: yes
      #yum:name=wget state=latest
      yum:
        name: wget
        state: latest
      tags:
        - packages
