---
- name: Register to Red Hat RHSM
  # I use the tag below to pick up unsubscribed hosts from the inventory
  hosts: tag_rhsm_false
  # need to be root in order to install and register
  become: yes
  become_method: sudo

  tasks:
    - name: Install OS Packages
      yum:
        name: subscription-manager
        state: present
      tags:
        - install

    - name: "Register host and subscribe (using tower survey)"
      ignore_errors: yes
      redhat_subscription:
        state: present
        username: '{{rhn_username}}'
        password: '{{rhn_password}}'
        #autosubscribe: true
        force_register: true
        pool: '{{rhn_pool_id}}'
      tags:
        - register
