---
- name: Register to Red Hat RHSM
  # I use the tag below to pick up unsubscribed hosts from the inventory
  hosts: tag_rhsm_false

  tasks:
    - name: Register host and subscribe (using tower survey)
      redhat_subscription:
        state: present
        username: '{{rhn_username}}'
        password: '{{rhn_password}}'
        #autosubscribe: true
        pool_ids: '{{rhn_pool_id}}'
      tags:
        - RHSM
