---
- name: Test telegram module
  hosts: localhost
  connection: local

  tasks:
    - name: Send test message
      command: /usr/bin/say "Is it working?"
      #telegram:
      #  token: "*****"
      #  chat_id: *****
      #  msg: "Ansible playbook calling"
      tags:
        - text
