---
# This playbook provides VM orchestration on Amazon EC2

- name: VM and Application Orchestration Demo
  hosts: localhost
  connection: local
  gather_facts: no

  pre_tasks:
    - name: Log what we are doing
      shell: /usr/bin/echo 'Foo'

  roles:
    - { role: linux, tags: ["instances", "linux"], when: ec2_os_type == 'linux' }
    - { role: windows, tags: ["instances", "windows"], when: ec2_os_type == 'windows' }

- name: Configure common options across new Linux instances
  hosts: justcreatedlinux
  gather_facts: yes

  roles:
    - linux/postcreate

- name: Configure common options across new Windows instances
  hosts: justcreatedwindows
  gather_facts: yes

  roles:
    - postcreatewindows

  post_tasks:
    - name: Log what we are doing
      shell: /usr/bin/echo 'Foo'
