---
# This playbook provides VM orchestration on Amazon EC2

- name: VM and Application Orchestration Demo
  hosts: localhost
  connection: local
  gather_facts: no
  ignore_errors: True

  pre_tasks:
    - name: Callback to BPM using pid
      uri:
        method: POST
        user: bpmsAdmin
        password: redhat1!
        url: "http://ec2-52-212-76-182.eu-west-1.compute.amazonaws.com:8080/business-central/rest/runtime/com.gatwick.demo:gatwickdemoproject:1.0/process/instance/{{pid}}/signal?signal=startRef"
      tags:
        - always

  roles:
    - { role: 'linux/provision', tags: ["instances", "linux"], when: ec2_os_type == 'linux' }
    - { role: 'windows/provision', tags: ["instances", "windows"], when: ec2_os_type == 'windows' }

- name: Configure common options across new Linux instances
  hosts: justcreatedlinux
  gather_facts: yes
  become: yes
  become_method: sudo

  roles:
    - linux/postcreate
    - { role: 'linux/apps/web', tags: ["apps", "linux"], when: ec2_instance_app == 'web' }
    # we can add more apps roles here if we wanted, or perhaps an array of apps would be better to loop through?

- name: Configure common options across new Windows instances
  hosts: justcreatedwindows
  gather_facts: no

  #roles:
  #  - windows/postcreate

  post_tasks:
    - name: Callback to BPM using pid
      uri:
        method: POST
        user: bpmsAdmin
        password: redhat1!
        url: "http://ec2-52-212-76-182.eu-west-1.compute.amazonaws.com:8080/business-central/rest/runtime/com.gatwick.demo:gatwickdemoproject:1.0/process/instance/{{pid}}/signal?signal=stopRef"
      tags:
        - always
