---
# This playbook provides VM orchestration on Amazon EC2

- name: VM and Application Orchestration Demo
  hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - { role: linux, tags: ["instances", "linux"], when: ec2_os_type == 'linux' }
    - { role: windows, tags: ["instances", "windows"], when: ec2_os_type == 'windows' }
    - postcreate
