---
# This playbook contains post VM creation tasks that will be run on all Linux nodes.
- hosts: tag_Name_just_created_linux
  become: yes
  become_method: sudo
  gather_facts: true

- name: Install Samba and misc packages
  yum: name={{item}} state=latest
  with_items:
    - samba
    - samba-client
    - samba-winbind
    - samba-winbind-clients
    - samba-winbind-krb5-locator
    - wget
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
