---
- hosts: tag_Name_just_created_linux
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:

    - name: Install Samba and misc packages
      yum: name={{item}} state=present
      with_items:
        - samba
        - samba-client
        - samba-winbind
        - samba-winbind-clients
        - wget
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
