---
# This playbook contains post VM creation tasks that will be run on all Linux nodes.

- name: Create user accounts
  user: name=phil comment="Phil Griffiths" uid=1101 groups=wheel append=yes

- name: Install and configure NTP
  yum: name=ntp state=latest
  #template: src=/templates/ntp.conf.j2 dest=/etc/ntp.conf
  #notify: restart ntp
