---
# This playbook contains common plays that will be run on all nodes.

- block:
    - shell: echo "This command was run on `/bin/date`"
    - user: name=phil comment="Phil Griffiths" uid=1101 groups=wheel append=yes
  when: ansible_distribution == 'RedHat'
