---

  vars:
    ec2_region: eu-west-1
    ec2_zone: eu-west-1b
    ec2_ami: ami-2bc3a858
    ec2_count: 1

   - block:
     - name: 'Create Amazon VM Instance(s)'
       ec2:
         key_name: "ansible-tower"
         # set in vars: above just for convenience
         region: "{{ ec2_region }}"
         zone: "{{ ec2_zone }}"
         image: "{{ ec2_ami }}"
         count: "{{ ec2_count }}"
         # passed as extra_vars from BPM form input
         instance_type: "{{ ec2_instance_type }}"
         wait: yes
         group: launch-wizard-1
         vpc_subnet_id: subnet-0f120178
         assign_public_ip: yes
         monitoring: no
         state: present
       register: newmachines

     - name: Wait for SSH to start
       wait_for:
         host: "{{ newmachines.instances[0].public_ip }}"
         port: 22
         timeout: 300
       delegate_to: localhost

     - name: Add the machine to in memory inventory
       add_host:
         hostname: "{{ newmachines.instances[0].public_ip }}"
         groups: amazon

     - name: Configure instance hostname
       set_fact: hostname_to_use={{ vm_hostname }}

     when: '"create" in vm_env_action'
     become: no
     ignore_errors: no


   - block:
     - name: 'Destroy Amazon VM instance(s)'
       shell: /bin/true

     when: '"destroy" in vm_env_action'
     become: no
