---
# This playbook creates user accounts.

- name: add user accounts
  user: name={{ item.name }} state=present groups={{ item.groups }}
  with_items:
    - {name: 'pgriffit', groups: 'wheel' }
    - {name: 'fred', groups: 'games' }
    - {name: 'wilma', groups: 'games' }
    - {name: 'jboss', groups: 'fuse' }
  tags:
    - users
    
  #include: otherstuff.yml
