---
# This playbook installs necessary OS packages.

- name: Install Java 1.7 and some basic dependencies
      yum: name={{item}} state=present
      with_items:
        - unzip
        - java-1.7.0-openjdk
        - libselinux-python
        - libsemanage-python
      tags:
        - packages
