---
# This playbook configures VMs across multiple cloud providers

- name: apply common configuration to all nodes
  hosts: cloud

  roles:
    - common

- name: configure in Amazon AWS EC2
  hosts: amazon

  roles:
    - amazon

- name: configure in Microsoft Azure
  hosts: azure
  remote_user: pgriffit

  roles:
    - azure
