---
# This playbook configures haproxy and some web servers for a rolling upgrade demo

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common

- name: Configure the haproxy server
  hosts: haproxy

  roles:
    - haproxy

- name: Configure the web servers sitting behind the haproxy
  hosts: webservers

  roles:
    - webservers
