---
- name: Delete Azure compute stack by removing resource group
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Delete resource group
      azure_rm_resourcegroup:
        name: tower-demos-rg1
        state:absent
        force: yes

   