---
- name: Setup an vsphere ESXI VM from a template
  hosts: localhost
  connection: local

  tasks:
    - name: Create an ESXi VM Guest From Template
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ hostname }}'
        from_template: yes
        template_src: tpl-rhel7-minimal
        cluster: Demonstrations
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
        esxi:
          datacenter: EMEA CloudLab
          hostname: cloud12-acc.gps.hst.ams2.redhat.com

    - name: Reconfigure VMware VM
      vsphere_guest:
        guest: "{{ hostname }}"
        state: reconfigured
        force: true
        vm_extra_config:
          notes: VM Created Using Ansible Tower
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpus }}"
