---
- name: Setup an vsphere ESXI VM from a template
  hosts: localhost
  connection: local

  tasks:
    - name: Create an ESXi VM Guest From Template
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        from_template: yes
        template_src: tpl-rhel7-minimal
        cluster: Demonstrations
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: "VM Created Using Ansible Tower"
        esxi:
          datacenter: EMEA CloudLab
          hostname: cloud12-acc.gps.hst.ams2.redhat.com

    - name: Reconfigure VMware VM
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        state: reconfigured
        force: true
        vm_hardware:
          memory_mb: '{{ vm_memory }}'
          num_cpus: '{{ vm_cpus }}'

    - name: Gather and act on vmware guest facts
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        vmware_guest_facts: yes
      register: vm_facts

    - debug: var=vm_facts
