---
- name: Create a RHEV based VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    hostname: pgriffit-ansible-test1

  tasks:
    - name: Create a VM called {{ hostname }}
      ovirt:
        url: https://10.33.11.20
        user: '{{ username }}@internal'
        password: '{{ password }}'
        image: pgriffit-rhel7-base-template
        zone: Default
        resource_type: template
        instance_name: '{{ hostname }}'
        instance_type: server123.
