---
- name: Setup an Azure instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Azure VM with defaults
      azure_rm_virtualmachine:
        resource_group: rg1
        name: "my-azure-vm"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
