---
- name: Create a vCenter VM from a template
  hosts: localhost
  connection: local

  vars:
    vmotion_host: cloud07-acc.gps.hst.ams2.redhat.com

  tasks:
    - name: Create VM guest from the template
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        from_template: yes
        template_src: tpl-rhel7-minimal
        cluster: Demonstrations
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: "VM Created Using Ansible Tower"
        esxi:
          datacenter: EMEA CloudLab
          hostname: cloud12-acc.gps.hst.ams2.redhat.com

    - name: Reconfigure VMware VM (add CPU and RAM)
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        state: reconfigured
        force: true
        vm_hardware:
          memory_mb: '{{ vm_memory }}'
          num_cpus: '{{ vm_cpus }}'

    - name: Gather VM guest facts that could be acted upon
      vsphere_guest:
        vcenter_hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        guest: '{{ vm_hostname }}'
        vmware_guest_facts: yes
      register: vm_facts

    - debug: var=vm_facts

    - name: Perform vMotion of VM
      local_action:
        module: vmware_vmotion
        hostname: 10.39.164.21
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: False
        vm_name: '{{ vm_hostname }}'
        destination_host: '{{ vmotion_host }}'
