---
- name: RHV Discovery
  hosts: all

  tasks:

  - name: Authenticate against RHVM
    ovirt_auth:
      url: '{{ url }}'
      username: '{{ username }}'
      password: '{{ password }}'

  - name: List VMs
    ovirt_vms_facts:
