---
- name: Setup an vsphere ESXI VM from a template
  hosts: localhost
  connection: local

  tasks:
    - name: Create an ESXi VM Guest From Template
      vmware_guest:
        name: tower-generated-vm
        template: RHEL7.4-template-vmware
        cluster: LAB
        datacenter: LNLAB-OPNSTK
        #state: poweredon
        #wait_for_ip_address: true
        #validate_certs: False
