- hosts: haproxy

  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:

  - name: Make sure haproxy is installed
    yum: pkg=haproxy state=latest

  - name: write the haproxy config file
    template: src=templates/haproxy.j2 dest=/etc/haproxy/haproxy.cfg
    ignore_errors: false
    notify:
    - restart haproxy

